generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MenuItem
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          menu_item
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      fields:
        name: {label: Наименование}
        price: {label: Цена}
        Group: {label: Раздел}
        menu_group_id: {label: Раздел }
        created_at: {date_format: dd/MM/yyyy HH:mm, label: Дата создания }
        updated_at: {date_format: dd/MM/yyyy HH:mm, label: Дата изменения }
        index: {label: Индекс }
        is_active: {label: Есть в наличии? }

      list:
        display: [index, name, is_active, price, Group, created_at]
        title: Список блюд
        max_per_page: 0
        actions:
          _new: ~
          save_order: {label: Сохранить индекс }
        table_method: getForAdmin
        sort: ['index','asc']
      filter:
        display: [name, menu_group_id]
      form: ~
      edit:
        title: Редактирование блюда "%%name%%"
      new:
        title: Новое блюдо
