generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MenuItem
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          menu_item
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: {label: Наименование}
        price: {label: Цена}
        Group: {label: Раздел}
        menu_group_id: {label: Раздел }
        created_at: {date_format: dd/MM/yyyy HH:mm, label: Дата создания }
        updated_at: {date_format: dd/MM/yyyy HH:mm, label: Дата изменения }
      list:
        display: [name, price, Group, created_at, updated_at]
        title: Список блюд
        max_per_page: 10
      filter:
        display: [name, menu_group_id]
      form:
        display: [name, price, menu_group_id]
      edit:
        title: Редактирование блюда "%%name%%"
      new:
        title: Новое блюдо
