generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MenuItem
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          menu_item
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name, price, Group, created_at, updated_at]
      filter:
        display: [name, menu_group_id]
      form:    ~
      edit:    ~
      new:     ~
