<?php

/**
 * BaseComponent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $amount
 * 
 * @method string    getName()   Returns the current record's "name" value
 * @method integer   getAmount() Returns the current record's "amount" value
 * @method Component setName()   Sets the current record's "name" value
 * @method Component setAmount() Sets the current record's "amount" value
 * 
 * @package    marcel
 * @subpackage model
 * @author     Dziamid
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComponent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('component');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('amount', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}