<?php

/**
 * BaseDesk
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $index
 * @property string $number
 * @property Doctrine_Collection $Bills
 * 
 * @method integer             getIndex()  Returns the current record's "index" value
 * @method string              getNumber() Returns the current record's "number" value
 * @method Doctrine_Collection getBills()  Returns the current record's "Bills" collection
 * @method Desk                setIndex()  Sets the current record's "index" value
 * @method Desk                setNumber() Sets the current record's "number" value
 * @method Desk                setBills()  Sets the current record's "Bills" collection
 * 
 * @package    marcel
 * @subpackage model
 * @author     Dziamid
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDesk extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('desk');
        $this->hasColumn('index', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('number', 'string', 20, array(
             'type' => 'string',
             'unique' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Bill as Bills', array(
             'local' => 'id',
             'foreign' => 'desk_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}