<?php

/**
 * BaseMenuItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $price
 * @property integer $menu_group_id
 * @property integer $index
 * @property boolean $is_active
 * @property integer $discount
 * @property Doctrine_Collection $Items
 * @property MenuGroup $Group
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method integer             getPrice()         Returns the current record's "price" value
 * @method integer             getMenuGroupId()   Returns the current record's "menu_group_id" value
 * @method integer             getIndex()         Returns the current record's "index" value
 * @method boolean             getIsActive()      Returns the current record's "is_active" value
 * @method integer             getDiscount()      Returns the current record's "discount" value
 * @method Doctrine_Collection getItems()         Returns the current record's "Items" collection
 * @method MenuGroup           getGroup()         Returns the current record's "Group" value
 * @method MenuItem            setName()          Sets the current record's "name" value
 * @method MenuItem            setPrice()         Sets the current record's "price" value
 * @method MenuItem            setMenuGroupId()   Sets the current record's "menu_group_id" value
 * @method MenuItem            setIndex()         Sets the current record's "index" value
 * @method MenuItem            setIsActive()      Sets the current record's "is_active" value
 * @method MenuItem            setDiscount()      Sets the current record's "discount" value
 * @method MenuItem            setItems()         Sets the current record's "Items" collection
 * @method MenuItem            setGroup()         Sets the current record's "Group" value
 * 
 * @package    marcel
 * @subpackage model
 * @author     Dziamid
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMenuItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('menu_item');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('price', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
        $this->hasColumn('menu_group_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('index', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('discount', 'integer', 3, array(
             'type' => 'integer',
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Item as Items', array(
             'local' => 'id',
             'foreign' => 'menu_item_id'));

        $this->hasOne('MenuGroup as Group', array(
             'local' => 'menu_group_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}