generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MenuGroup
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          menu_group
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        items_total: {label: Всего }
        name: {label: Наименование }
      list:
        title: Разделы меню
        display: [name, _type, items_total]
        batch_actions: []
        max_per_page: 0
      filter:
        display: [name, type]
      form:    ~
      edit:
        title: Редактирование раздела "%%name%%"
      new:
        title: Новый раздел
