generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MenuGroup
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          menu_group
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        items_total: {label: Всего }
        name: {label: Наименование }
        type: {label: Кухня/бар }
        _type: {label: Кухня/бар }
        index: {label: Индекс }

      list:
        title: Разделы меню
        display: [index, name, _type, items_total]
        batch_actions: []
        max_per_page: 0
        actions:
          _new: ~
          save_order: {label: Сохранить индекс }
        table_method: getForAdmin
        sort: ['index', 'asc']

      filter:
        display: [name, type]
      form:    ~
      edit:
        title: Редактирование раздела "%%name%%"
      new:
        title: Новый раздел
