<?php

/**
 * BillTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BillTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object BillTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Bill');
  }
  public function getMaxNumber()
  {
    $date = new DateTime();
    $date->setDate($date->format('Y'), 1, 1)->setTime(0,0,0);
    
    $max = $this->createQuery('b')
      ->select('b.number')
      ->where('b.created_at > ?', $date->format('Y-m-d H:i:s'))
      ->orderBy('b.number DESC')
      ->limit(1)
      ->fetchOne(array(),Doctrine_Core::HYDRATE_SINGLE_SCALAR);
    
    return $max !== null ? $max + 1 : 1;
  }
}