<?php

/**
 * BillTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BillTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object BillTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Bill');
  }
  public function getMaxNumber()
  {
    $max = $this->createQuery('b')
      ->select('b.number')
      ->orderBy('b.number DESC')
      ->limit(1)
      ->fetchOne(array(),Doctrine_Core::HYDRATE_SINGLE_SCALAR);
    
    return $max !== null ? $max + 1 : 1;
  }
  public function getForAdminBill()
  {
    $q = $this->createQuery('b')
      ->leftJoin('b.Desk d')
      ->leftJoin('b.Items i');
    return $q;
  }
}