<?php

/**
 * Desk
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    marcel
 * @subpackage model
 * @author     Dziamid
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Desk extends BaseDesk
{
  public function getOpenBill()
  {
    $bills = $this->getBills();

    foreach ($bills as $bill)
    {
      if ($bill->isOpen())
      {
        return $bill;
      }
    }
    return false;
  }
}
