<?php

/**
 * Desk
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    marcel
 * @subpackage model
 * @author     Dziamid
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Desk extends BaseDesk
{
  public function getOpenBill()
  {
    $bills = $this->getBills();

    foreach ($bills as $bill)
    {
      if ($bill->isOpen())
      {
        return $bill;
      }
    }
    return new myNull();
  }
  public function open()
  {
    $bill = new Bill();
    $bill->setOpen(true);
    $bill->setDesk($this);
    $bill->save();
  }
  public function close()
  {
    if ($this->getOpenBill()->isNotNull())
    {
      $bill = $this->getOpenBill();
      $bill->setOpen(false);
      $bill->save();
    }
  }
}
