<?php

/**
 * ItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Item');
    }
    public function getGroupedByMenuItem($query)
    {
      $q = $this->createQuery('i')
        ->select('i.*,m.*')
        ->addSelect('SUM(i.quantity) as total_quantity')
        ->addSelect('SUM(i.quantity * i.price) as total_sum')
        ->groupBy('i.menu_item_id, i.price')
        ->leftJoin('i.MenuItem m')
        ->leftJoin('m.Group g');
      return $q;
    }
}