<?php

/**
 * MenuItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    marcel
 * @subpackage model
 * @author     Dziamid
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MenuItem extends BaseMenuItem
{
  public function __toString()
  {
    return (string)$this->getName();
  }
  public function getDiscountPrice()
  {
    $discount = $this->getDiscount() ? $this->getDiscount() : 0;
    return $this->getPrice() * (100 - $this->getDiscount()) / 100;
  }
}
