<?php

/**
 * MenuItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MenuItemTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object MenuItemTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('MenuItem');
  }
  public function getChoices()
  {
    $q = $this->createQuery('i')
      ->select('i.name, i.menu_group_id')
      ->orderBy('i.name');
      
    return $q->execute(array(), Doctrine::HYDRATE_ARRAY);

  }
  /**
   * Efficiency query
   *
   */
  public function getForAdmin(Doctrine_Query $q)
  {
    $q->leftJoin(sprintf('%s.Group g',$q->getRootAlias()));
  }
  
  /**
   *  Get MenuItems for menu component
   *
   */
  public function getMenuItems()
  {
    Doctrine_Manager::getInstance()->setAttribute(Doctrine_Core::ATTR_USE_DQL_CALLBACKS, true);

    $q = $this->createQuery('i')
      ->leftJoin('i.Group g')
      ->where('i.is_active = ?', true)
      ->orderBy('i.index asc');
      
    $return = $q->execute(array(),  Doctrine_Core::HYDRATE_ARRAY);
    
    Doctrine_Manager::getInstance()->setAttribute(Doctrine_Core::ATTR_USE_DQL_CALLBACKS, false);
    
    return $return;
  }
}