<?php

/**
 * MenuGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    marcel
 * @subpackage model
 * @author     Dziamid
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MenuGroup extends BaseMenuGroup
{
  const TYPE_KITCHEN = 1;
  const TYPE_BAR = 2;
  
  protected static
    $type_string = array(
      1 => 'Кухня',
      2 => 'Бар'
    ),
    $type_classname = array(
      1 => 'kitchen',
      2 => 'bar'      
    );

  public function __toString()
  {
    return (string)$this->getName();
  }
  public function getItemsTotal()
  {
    return $this->getItems()->count();
  }
  public function getTypeString()
  {
    return self::$type_string[$this->getType()];
  }
  public function getTypeClassname()
  {
    return self::$type_classname[$this->getType()];
  }
  public static function getTypes()
  {
    return self::$type_string;
  }
  public static function getTypeName($key)
  {
    return isset(self::$type_string[$key]) ? self::$type_string[$key] : false;
  }
}
