<?php

/**
 * MenuGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MenuGroupTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object MenuGroupTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('MenuGroup');
  }
  public function getForList()
  {
    $q = $this->createQuery('g')
      ->leftJoin('g.Items i')
      ->orderBy('g.type');
    
    return $q->execute();
  }
}