<?php

/**
 * MenuGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MenuGroupTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object MenuGroupTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('MenuGroup');
  }
  public function getMenuTree()
  {
    Doctrine_Manager::getInstance()->setAttribute(Doctrine_Core::ATTR_USE_DQL_CALLBACKS, true);

    $q = $this->createQuery('g')
      ->orderBy('g.root_id')
      ->addOrderBy('g.lft')
      ->where('g.root_id NOT NULL');

    Doctrine_Manager::getInstance()->setAttribute(Doctrine_Core::ATTR_USE_DQL_CALLBACKS, false);
      
    return $q->execute(array(),  Doctrine_Core::HYDRATE_ARRAY_HIERARCHY);
  }
  //public function getForList()
  //{
  //  //don't show soft deleted groups and items
  //  Doctrine_Manager::getInstance()->setAttribute(Doctrine_Core::ATTR_USE_DQL_CALLBACKS, true);
  //  $return = $this->createQuery('g')
  //    ->leftJoin('g.Items i')
  //    ->orderBy('g.type, g.index, i.index')
  //    ->execute();
  //    
  //  Doctrine_Manager::getInstance()->setAttribute(Doctrine_Core::ATTR_USE_DQL_CALLBACKS, false);
  //
  //  return $return;
  //}
  /**
   * Efficiency query
   *
   */
  public function getForAdmin()
  {
      $q = $this->createQuery('m')
        ->orderBy('m.root_id')
        ->addOrderBy('m.lft');
        
      return $q;
  }
}