<?php

/**
 * MenuItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MenuItemTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object MenuItemTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('MenuItem');
  }
  public function getChoices()
  {
    $q = $this->createQuery('i')
      ->innerJoin('i.Group g');
      
    $items = $q->execute();
    $empty = array('label'=>'','data-group'=>'');
    $choices = array();
    $choices[''] = $empty;
    foreach ($items as $item)
    {
      $choices[$item->getId()] = array('label'=>(string)$item,'data-group'=>$item->getGroup()->getId());
    }
    return $choices;
  }
  /**
   * Efficiency query
   *
   */
  public function getForAdmin(Doctrine_Query $q)
  {
    $q->leftJoin(sprintf('%s.Group g',$q->getRootAlias()));
  }
  
  /**
   *  Get MenuItems for menu component
   *
   */
  public function getMenuItems()
  {
    $q = $this->createQuery('i')
      ->leftJoin('i.Group g');
      
    return $q->execute(array(),  Doctrine_Core::HYDRATE_ARRAY);

  }
}