<?php

/**
 * MenuGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    marcel
 * @subpackage model
 * @author     Dziamid
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MenuGroup extends BaseMenuGroup
{
  public function getItemsTotal()
  {
    return $this->getItems()->count();
  }
}
