# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  menus:
    frontend:
      #child_class:  ioMenuItem (already set in ioMenu class by default)
      children:
        home:
          name:    home
          label:   Главная
          route:   homepage
        desk:
          name:    desk
          label:   Столы
          route:   desk
        admin:
          label:   Администрирование
          route:   admin
          credentials: [admin]
          children:
            bill:
              label:   Счета
              route:   admin_bill
            admin_desk:
              label:   Столы
              route:   admin_desk
            menu_item:
              name:    menu_item
              label:   Блюда
              route:   menu_item
            menu_group:
              label:   Разделы
              route:   menu_group
        stat:
          label: Статистика
          route: stat
          credentials: [admin]
          children:
            admin_item:
              label: Общая
              route: admin_item
            stat_item:
              label: По наименованию
              route: stat_item
            #stat_group:
            #  label: По разделам
            #  route: stat_group
          
  use_ajax: true

  billheader:
    company: ООО "Смарт Фуд"
    cafe: Кафе "Марсель"
    waiter: Тишко А.Г.
    
  sf_guard_plugin:
    success_signin_url: @homepage
    success_signout_url: @homepage
    routes_register: false