desk:
  class: sfDoctrineRouteCollection
  options:
    model: Desk
    module: desk
    object_actions: {open: post, close: post}

bill:
  class: sfDoctrineRouteCollection
  options:
    model: Bill
    module: bill
    object_actions: {select: post}

item:
  class: sfDoctrineRouteCollection
  options:
    model: Item
    module: item
    object_actions: {unselect: post}
    
menu_item:
  class: sfDoctrineRouteCollection
  options:
    model: MenuItem
    module: menu_item

menu_group:
  class: sfDoctrineRouteCollection
  options:
    model: MenuGroup
    module: MenuGroup
    with_wildcard_routes: true
    
homepage:
  url:   /
  param: { module: home, action: index }

