stat:
  url: /stat
  param: { module: home, action: stat}

desk:
  class: sfDoctrineRouteCollection
  options:
    model: Desk
    module: desk
    object_actions: {open: post}

bill:
  class: sfDoctrineRouteCollection
  options:
    model: Bill
    module: bill
    object_actions: {close: post, print: post, discount: post}

item:
  class: sfDoctrineRouteCollection
  options:
    model: Item
    module: item
    object_actions: {unselect: post, add: post}
    
admin:
  url:   /admin
  param: { module: home, action: admin }
  
menu_item:
  class: sfDoctrineRouteCollection
  options:
    model: MenuItem
    module: MenuItem
    prefix_path: /admin/menu/item
    with_wildcard_routes: true
    object_actions: {select: post}

menu_group:
  class: sfDoctrineRouteCollection
  options:
    model: MenuGroup
    module: MenuGroup
    prefix_path: /admin/menu/group
    with_wildcard_routes: true

admin_desk:
  class: sfDoctrineRouteCollection
  options:
    model: Desk
    module: adminDesk
    prefix_path: /admin/desk
    with_wildcard_routes: true

admin_item:
  class: sfDoctrineRouteCollection
  options:
    model: Item
    module: adminItem
    prefix_path: /admin/item
    with_wildcard_routes: true

admin_bill:
  class: sfDoctrineRouteCollection
  options:
    model: Bill
    module: adminBill
    prefix_path: /admin/bill
    with_wildcard_routes: true
    
stat_item:
  class: sfDoctrineRouteCollection
  options:
    model: Item
    module: statItem
    prefix_path: /stat/item
    with_wildcard_routes: true

stat_group:
  class: sfDoctrineRouteCollection
  options:
    model: Item
    module: statGroup
    prefix_path: /stat/group
    with_wildcard_routes: true

homepage:
  url:   /
  param: { module: home, action: index }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }