stats:
  url: /stats
  param: { module: home, action: stats}

desk:
  class: sfDoctrineRouteCollection
  options:
    model: Desk
    module: desk
    object_actions: {open: post, close: post}

bill:
  class: sfDoctrineRouteCollection
  options:
    model: Bill
    module: bill
    object_actions: {select: post}

item:
  class: sfDoctrineRouteCollection
  options:
    model: Item
    module: item
    object_actions: {unselect: post}
    
admin:
  url:   /admin
  param: { module: home, action: admin }
  
menu_item:
  class: sfDoctrineRouteCollection
  options:
    model: MenuItem
    module: MenuItem
    prefix_path: /admin/menu/item
    with_wildcard_routes: true


menu_group:
  class: sfDoctrineRouteCollection
  options:
    model: MenuGroup
    module: MenuGroup
    prefix_path: /admin/menu/group
    with_wildcard_routes: true

admin_desk:
  class: sfDoctrineRouteCollection
  options:
    model: Desk
    module: adminDesk
    prefix_path: /admin/desk
    with_wildcard_routes: true 
    
homepage:
  url:   /
  param: { module: home, action: index }

