desk:
  class: sfDoctrineRouteCollection
  options:
    model: Desk
    module: desk
bill:
  class: sfDoctrineRouteCollection
  options:
    model: Bill
    module: bill
item:
  class: sfDoctrineRouteCollection
  options:
    model: Item
    module: item
menu_item:
  class: sfDoctrineRouteCollection
  options:
    model: MenuItem
    module: menu_item
    object_actions: {select: post}
    
homepage:
  url:   /
  param: { module: home, action: index }

