generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Desk
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          admin_desk
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        number: {label: Номер}
        created_at: {label: Добавлено}
        updated_at: {label: Изменено}
      list:
        display: [number, created_at, updated_at]
        title: Список столов
      filter:
        display: [number]
      form:    ~
      edit:
        title: Редактирование стола "%%number%%"
      new:
        title: Новый стол
