generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Item
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          admin_item
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        Bill: {label: № счёта }
        bill_id: {label: № счёта }
        MenuItem: {label: Наименование }
        total: {label: Всего }
        price: {label: Цена }
        created_at: {date_format: dd/MM/yyyy HH:mm, label: Дата создания }

        quantity: {label: Кол-во }

      list:
        display: [Bill, MenuItem, quantity, price, total, created_at]
        #title is overriden in indexSuccess
        #title: Статистика
        table_method: getItems
        object_actions: []
        batch_actions: []
        actions: []
        max_per_page: 20
        sort: ['created_at','desc']
      filter:
        display: [~filterToday, bill_id]
      form:    ~
      edit:    ~
      new:     ~
