generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Item
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          admin_item
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        Bill: {label: № счёта}
        MenuItem: {label: Наименование }
        total: {label: Кол-во}
        created_at: {label: Добавлено}

      list:
        title: Статистика по наименованию
        display: [MenuItem, total]
        table_method: getForStat
        object_actions: []
        batch_actions: []
        actions: []
      filter:
        display: [created_at]
      form:    ~
      edit:    ~
      new:     ~
