all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      #dsn: <?php echo sprintf('sqlite:%s/../data/db/sqlite.db',dirname(__FILE__))."\n" ?>
      dsn: mysql:host=localhost;dbname=marcel
      username: root
      password: null
