generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Bill
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          admin_bill
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at: {date_format: dd/MM/yyyy HH:mm, label: Дата создания }
        number: {label: № счёта }
        Desk: {label: № стола }
        desk_id: {label: № стола }
        open: {label: Счёт открыт? }
        is_printed: {label: Счёт распечатан? }
        is_hidden: {label: Счёт скрыт? }
        total: {label: Сумма }
      list:
        title: Счета
        sort: ['number','desc']
        display: [number, Desk, total, open, is_hidden, created_at]
        max_per_page: 10
        actions: []
        table_method: getForAdminBill
        batch_actions:
          hide: {label: Скрыть счета }
      filter:
        display: [number, desk_id, open, created_at]
      form:    ~
      edit:
        title: Редактирование счета №%%number%%
      new:     ~
