generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Item
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          stat_item
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        MenuItem: {label: Наименование }
        menu_item_id: {label: Наименование }
        price: {label: Цена }
        total_quantity: {label: Кол-во }
        total_sum: {label: Сумма }
        menu_group: {label: Раздел }
        type: {label: Кухня/бар }
        bill_is_hidden: {label: Для бухгалтера }

      list:
        title: Статистика по наименованию
        table_method: getGroupedByMenuItem
        display: [MenuItem, _type, price, total_quantity, total_sum]
        object_actions: []
        batch_actions: []
        actions: []
          #save_report action is overriden in indexSuccess (to make it a post link)
          #save_report: {label: Сохранить отчет}
        max_per_page: 0
        sort: ['total_sum','desc']
      filter:
        display: [~filterToday, type, menu_group, menu_item_id, bill_is_hidden]
      form:    ~
      edit:    ~
      new:     ~
