generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Item
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          stat_item
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        MenuItem: {label: Наименование }
        menu_item_id: {label: Наименование }
        price: {label: Цена }
        total_quantity: {label: Кол-во }
        total_sum: {label: Сумма }
        menu_group: {label: Раздел }
      list:
        title: Статистика по наименованию
        table_method: getGroupedByMenuItem
        display: [MenuItem, price, total_quantity, total_sum ]
        object_actions: []
        batch_actions: []
        actions: []
        max_per_page: 10
        sort: ['total_sum','desc']
      filter:
        display: [~filterToday, menu_group, menu_item_id]
      form:    ~
      edit:    ~
      new:     ~
