Bill:
  columns:
    number: integer
    desk_id: integer
    open:
      type: boolean
      notnull: true
      default: false
  relations:
    Desk:
      local: desk_id
      foreign: id
      foreignAlias: Bills

Item:
  columns:
    menu_item_id: integer
    bill_id: integer
    quantity: integer
  relations:
    Bill:
      local: bill_id
      foreign: id
      foreignAlias: Items
    MenuItem:
      local: menu_item_id
      foreign: id
      type: one
      foreignType: one

Desk:
  columns:
    number: integer
    
MenuItem:
  columns:
    name: string(255)
    price: intger(10)
    menu_group_id: integer
  relations:
    MenuGroup:
      local: menu_group_id
      foreign: id
      foreignAlias: Items
      alias: Group
MenuGroup:
  columns:
    name: string(255)
    slug: string(255)
    # type - kitchen (1), bar (2)
    type:
      type: integer
      default: 1
      notnull: true