Bill:
  actAs:
    Timestampable: ~
  columns:
    number:
      type: integer
      unique: true
    desk_id: integer
    open:
      type: boolean
      notnull: true
      default: false
  relations:
    Item:
      local: id
      foreign: bill_id
      alias: Items
      foreignAlias: Bill
      type: many
      foreignType: one
      cascade: [delete]
    Desk:
      local: desk_id
      foreign: id
      foreignAlias: Bills

Item:
  actAs:
    Timestampable: ~
  columns:
    menu_item_id: integer
    bill_id: integer
    quantity: integer
    price: integer(10)
  relations:
    MenuItem:
      local: menu_item_id
      foreign: id
      type: one
      foreignType: one

Desk:
  actAs:
    Timestampable: ~
  columns:
    number:
      type: integer
      unique: true
    
MenuItem:
  actAs:
    Timestampable: ~
    SoftDelete: ~
  columns:
    name: string(255)
    price: intger(10)
    menu_group_id: integer

MenuGroup:
  actAs:
    Timestampable: ~
    SoftDelete: ~
  columns:
    name: string(255)
    slug: string(255)
    # type - kitchen (1), bar (2)
    type:
      type: integer
      default: 1
      notnull: true
  relations:
    MenuItem:
      type: many
      foreignType: one
      local: id
      foreign: menu_group_id
      alias: Items
      foreignAlias: Group
      cascade: [delete]
      
Component:
  actAs:
    Timestampable: ~
  columns:
    name: string(255)
    amount: integer